Update Gitlab 8.3.2

diff --git a/GitLab/scripts/postinst b/GitLab/scripts/postinst
--- a/GitLab/scripts/postinst
+++ b/GitLab/scripts/postinst
@@ -1,63 +1,67 @@
 #!/bin/sh
 # Copyright (c) 2000-2015 Synology Inc. All rights reserved.
 
+[ "$SYNOPKG_PKG_STATUS" = UPGRADE ] && exit 0
+
 . "$(dirname $0)"/common
 
-DB_HOST=$(ip address show docker0 | grep inet | awk '{print $2}' | cut -f1 -d/ | head -n 1)
-DB_USER="$PKG_SHORT"
-API=/usr/syno/bin/synowebapi
-GITLAB_PROFILE="$TARGET_PATH"/config/synology_gitlab
-REDIS_PROFILE="$TARGET_PATH"/config/synology_gitlab_redis
+HTTP_PORT="$pkgwizard_http_port"
+SSH_PORT="$pkgwizard_ssh_port"
+DB_NAME="$pkgwizard_db_name"
+DB_USER="$pkgwizard_db_user"
+DB_PASS="$pkgwizard_db_password"
+MARIADB_PASS="$pkgwizard_mysql_password"
+CI_PARAPHRASE="$(openssl rand -base64 48 | sed 's,/,_,g')"
+HOSTNAME="$pkgwizard_hostname"
+ADMIN_EMAIL="$pkgwizard_admin_email"
+SMTP_ENABLE="$pkgwizard_smtp_enable"
+SMTP_ADDR="$pkgwizard_smtp_address"
+SMTP_PORT="$pkgwizard_smtp_port"
+SMTP_USER="$pkgwizard_smtp_user"
+SMTP_PASS="$pkgwizard_smtp_pass"
+SMTP_VERIFY="$pkgwizard_smtp_verify"
+SHARE="$pkgwizard_dataroot"
 
-if [ "$SYNOPKG_PKG_STATUS" != UPGRADE ]; then
-	HTTP_PORT="$pkgwizard_http_port"
-	SSH_PORT="$pkgwizard_ssh_port"
-	UNICORN_TIMEOUT="180"
-	DB_NAME="$pkgwizard_db_name"
-	DB_PASS="$(openssl rand -base64 48 | sed 's,/,_,g')"
-	MARIADB_PASS="${pkgwizard_mysql_password:+-p$pkgwizard_mysql_password}"
-	CI_PARAPHRASE="$(openssl rand -base64 48 | sed 's,/,_,g')"
-	HOSTNAME="$pkgwizard_hostname"
-	ADMIN_EMAIL="$pkgwizard_admin_email"
-	SMTP_ENABLE="$pkgwizard_smtp_enable"
-	SMTP_ADDR="$pkgwizard_smtp_address"
-	SMTP_PORT="$pkgwizard_smtp_port"
-	SMTP_USER="$pkgwizard_smtp_user"
-	SMTP_PASS="$pkgwizard_smtp_pass"
-	SMTP_VERIFY="$pkgwizard_smtp_verify"
-	SHARE="$pkgwizard_dataroot"
-	SQL="CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASS'; CREATE DATABASE IF NOT EXISTS \`$DB_NAME\` DEFAULT CHARACTER SET \`utf8\` COLLATE \`utf8_unicode_ci\`; GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'%';"
-
-	echo $SQL | mysql -uroot "$MARIADB_PASS"
-
-	(
-		echo HTTP_PORT="\"$HTTP_PORT\""
-		echo SSH_PORT="\"$SSH_PORT\""
-		echo UNICORN_TIMEOUT="\"180\""
-		echo DB_NAME="\"$DB_NAME\""
-		echo DB_PASS="\"$DB_PASS\""
-		echo CI_PARAPHRASE="\"$CI_PARAPHRASE\""
-		echo HOSTNAME="\"$HOSTNAME\""
-		echo ADMIN_EMAIL="\"$ADMIN_EMAIL\""
-		echo SMTP_ENABLE="\"$SMTP_ENABLE\""
-		echo SMTP_ADDR="\"$SMTP_ADDR\""
-		echo SMTP_PORT="\"$SMTP_PORT\""
-		echo SMTP_USER="\"$SMTP_USER\""
-		echo SMTP_PASS="\"$SMTP_PASS\""
-		echo SMTP_VERIFY="\"$SMTP_VERIFY\""
-		echo SHARE="\"$SHARE\""
-		
-	) > "$ETC_PATH"/config
-else
-	. "$ETC_PATH"/config
+if [ ! -z "$MARIADB_PASS" ]; then
+	echo "CREATE DATABASE IF NOT EXISTS \`$DB_NAME\` DEFAULT CHARACTER SET \`utf8\` COLLATE \`utf8_unicode_ci\`;"                         | mysql -uroot "-p$MARIADB_PASS"
+	echo "CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASS'; GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'%';"                 | mysql -uroot "-p$MARIADB_PASS"
+	echo "CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS'; GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost';" | mysql -uroot "-p$MARIADB_PASS"		
+elif [ ! mysql -u$DB_USER -p"$DB_PASS" $DB_NAME -e exit ]; then
+	log "$failed_db_connect"
+	exit 1
 fi
+
+(
+	echo HTTP_PORT="\"$HTTP_PORT\""
+	echo SSH_PORT="\"$SSH_PORT\""
+	echo UNICORN_TIMEOUT="\"$UNICORN_TIMEOUT\""
+	echo DB_NAME="\"$DB_NAME\""
+	echo DB_USER="\"$DB_USER\""
+	echo DB_PASS="\"$DB_PASS\""
+	echo CI_PARAPHRASE="\"$CI_PARAPHRASE\""
+	echo HOSTNAME="\"$HOSTNAME\""
+	echo ADMIN_EMAIL="\"$ADMIN_EMAIL\""
+	echo SMTP_ENABLE="\"$SMTP_ENABLE\""
+	echo SMTP_ADDR="\"$SMTP_ADDR\""
+	echo SMTP_PORT="\"$SMTP_PORT\""
+	echo SMTP_USER="\"$SMTP_USER\""
+	echo SMTP_PASS="\"$SMTP_PASS\""
+	echo SMTP_VERIFY="\"$SMTP_VERIFY\""
+	echo SHARE="\"$SHARE\""
+) > "$ETC_PATH"/config
+
 sed -i \
 	-e "s/__HTTP_PORT__/$HTTP_PORT/g" \
-	"$TARGET_PATH"/ui/config \
-	"$GITLAB_PROFILE"
+	"$TARGET_PATH"/ui/config 
+	
 sed -i \
+	-e "s/__REDIS_VERSION__/$REDIS_VERSION/g" \
+	"$REDIS_PROFILE"
+	
+sed -i \
+	-e "s/__HTTP_PORT__/$HTTP_PORT/g" \
 	-e "s/__SSH_PORT__/$SSH_PORT/g" \
-	-e "s/__UNICORN_TIMEOUT__/180/g" \
+	-e "s/__UNICORN_TIMEOUT__/$UNICORN_TIMEOUT/g" \
 	-e "s/__DB_HOST__/$DB_HOST/g" \
 	-e "s/__DB_NAME__/$DB_NAME/g" \
 	-e "s/__DB_USER__/$DB_USER/g" \
@@ -71,11 +75,12 @@ sed -i \
 	-e "s/__SMTP_USER__/$SMTP_USER/g" \
 	-e "s/__SMTP_PASS__/$SMTP_PASS/g" \
 	-e "s/__SMTP_VERIFY__/$([ "$SMTP_VERIFY" = true ] && echo peer || echo none)/g" \
+	-e "s/__GITLAB_VERSION__/$GITLAB_VERSION/g" \
 	-e "s/__SHARE__/$SHARE/g" \
 	"$GITLAB_PROFILE"
-
-docker pull quay.io/sameersbn/gitlab:8.2.3
-docker pull quay.io/sameersbn/redis:latest	
+	
+docker pull quay.io/sameersbn/gitlab:$GITLAB_VERSION
+docker pull quay.io/sameersbn/redis:$REDIS_VERSION	
 	
 $API --exec api=SYNO.Docker.Container version=1 method=create is_run_instantly=false profile="$(cat "$REDIS_PROFILE")"
 $API --exec api=SYNO.Docker.Container version=1 method=create is_run_instantly=false profile="$(cat "$GITLAB_PROFILE")"
diff --git a/GitLab/scripts/postuninst b/GitLab/scripts/postuninst
--- a/GitLab/scripts/postuninst
+++ b/GitLab/scripts/postuninst
@@ -9,20 +9,26 @@
 /usr/syno/bin/synowebapi --exec api=SYNO.Docker.Container version=1 method=delete name=synology_gitlab_redis force=true preserve_profile=false
 /usr/syno/bin/synowebapi --exec api=SYNO.Docker.Container version=1 method=delete name=synology_gitlab force=true preserve_profile=false
 
-docker rmi quay.io/sameersbn/redis:latest
-docker rmi quay.io/sameersbn/gitlab:8.2.3
+docker rmi quay.io/sameersbn/redis:$REDIS_VERSION
+docker rmi quay.io/sameersbn/gitlab:$GITLAB_VERSION
 
-if [ "$SYNOPKG_PKG_STATUS" != UPGRADE ]; then
-	DB_USER="$PKG_SHORT"
-	MARIADB_PASS="${pkgwizard_mysql_password:+-p$pkgwizard_mysql_password}"
+if [ "$pkgwizard_delete_data" = true ]; then
+	
 	SQL_DROP_USER="DROP USER '$DB_USER'@'%';"
+	SQL_DROP_USER_LOCAL="DROP USER '$DB_USER'@'localhost';"
 	SQL_DROP_DATABASE="DROP DATABASE \`$DB_NAME\`;"
 
-	if ! echo $SQL_DROP_USER | mysql -uroot "$MARIADB_PASS"; then
-		logger -p 0 "$PKG_NAME: failed to remove the database user $DB_USER"
+	if ! echo $SQL_DROP_USER | mysql -uroot -p"$pkgwizard_mysql_password"; then
+		logger -p 0 "$PKG_NAME: failed to remove user $DB_USER"
 		log "$failed_remove_db_user" "$DB_USER"
 	fi
-	if ! echo $SQL_DROP_DATABASE | mysql -uroot "$MARIADB_PASS"; then
+
+	if ! echo $SQL_DROP_USER_LOCAL | mysql -uroot -p"$pkgwizard_mysql_password"; then
+		logger -p 0 "$PKG_NAME: failed to remove local user $DB_USER"
+		log "$failed_remove_db_user" "$DB_USER"
+	fi
+	
+	if ! echo $SQL_DROP_DATABASE | mysql -uroot -p"$pkgwizard_mysql_password"; then
 		logger -p 0 "$PKG_NAME: failed to remove the database $DB_NAME"
 		log "$failed_remove_db" "$DB_NAME"
 	fi
diff --git a/GitLab/scripts/preinst b/GitLab/scripts/preinst
--- a/GitLab/scripts/preinst
+++ b/GitLab/scripts/preinst
@@ -11,8 +11,12 @@ if [ -z "$pkgwizard_dataroot" ]; then
 fi
 
 # check mariadb password
-MARIADB_PASS="${pkgwizard_mysql_password:+-p$pkgwizard_mysql_password}"
-if [ "$(mysqladmin ping "$MARIADB_PASS")" != "mysqld is alive" ]; then
+if [ ! -z "$pkgwizard_mysql_password" ]; then
+	if [ "$(mysqladmin ping -p"$pkgwizard_mysql_password")" != "mysqld is alive" ]; then
+		log "$failed_db_connect"
+		exit 1
+	fi
+elif [ ! mysql -u$pkgwizard_db_user -p"$pkgwizard_db_password" $pkgwizard_db_name -e exit ]; then
 	log "$failed_db_connect"
 	exit 1
 fi
diff --git a/GitLab/scripts/preuninst b/GitLab/scripts/preuninst
--- a/GitLab/scripts/preuninst
+++ b/GitLab/scripts/preuninst
@@ -6,10 +6,11 @@
 . "$(dirname $0)"/common
 
 # check mariadb password
-MARIADB_PASS="${pkgwizard_mysql_password:+-p$pkgwizard_mysql_password}"
-if [ "$(mysqladmin ping "$MARIADB_PASS")" != "mysqld is alive" ]; then
-	log "$failed_db_connect"
-	exit 1
-fi
+if [ "$pkgwizard_delete_data" = true ]; then
+	if [ "$(mysqladmin ping -p"$pkgwizard_mysql_password")" != "mysqld is alive" ]; then
+		log "$failed_db_connect"
+		exit 1
+	fi
+fi 
 
 exit 0
diff --git a/GitLab/scripts/preupgrade b/GitLab/scripts/preupgrade
--- a/GitLab/scripts/preupgrade
+++ b/GitLab/scripts/preupgrade
@@ -2,49 +2,22 @@
 # Copyright (c) 2000-2015 Synology Inc. All rights reserved.
 
 . "$(dirname $0)"/common
-
 . "$ETC_PATH"/config
 
-if [ "$pkgwizard_mysql_password" != PreservePassword49L8tnAL ]; then
-# check mariadb password
-	MARIADB_PASS="${pkgwizard_mysql_password:+-p$pkgwizard_mysql_password}"
-	if [ "$(mysqladmin ping "$MARIADB_PASS")" != "mysqld is alive" ]; then
-		log "$failed_db_connect"
-		exit 1
-	fi
+[ "$pkgwizard_db_name" ]      && DB_NAME="$pkgwizard_db_name"
+[ "$pkgwizard_db_user" ]      && DB_USER="$pkgwizard_db_user"
+[ "$pkgwizard_db_password" ]  && DB_PASS="$pkgwizard_db_password"
+
+# check database
+if [ ! mysql -u$DB_USER -p"$DB_PASS" $DB_NAME -e exit ]; then
+	log "$failed_db_connect"
+	exit 1
 fi
 
-[ "$pkgwizard_hostname" ]     && HOSTNAME="$pkgwizard_hostname"
-[ "$pkgwizard_admin_email" ]  && ADMIN_EMAIL="$pkgwizard_admin_email"
-[ "$pkgwizard_http_port" ]    && HTTP_PORT="$pkgwizard_http_port"
-[ "$pkgwizard_ssh_port" ]     && SSH_PORT="$pkgwizard_ssh_port"
-[ "$pkgwizard_smtp_enable_unchanged" != true ] && SMTP_ENABLE="$pkgwizard_smtp_enable_true"
-[ "$pkgwizard_smtp_address" ] && SMTP_ADDR="$pkgwizard_smtp_address"
-[ "$pkgwizard_smtp_port" ]    && SMTP_PORT="$pkgwizard_smtp_port"
-[ "$pkgwizard_smtp_user" ]    && SMTP_USER="$pkgwizard_smtp_user"
-[ "$pkgwizard_smtp_pass" != PreservePassword49L8tnAL ] && SMTP_PASS="$pkgwizard_smtp_pass"
-[ "$pkgwizard_smtp_verify_unchanged" != true ] && SMTP_VERIFY="$pkgwizard_smtp_verify_true"
+/usr/syno/bin/synowebapi --exec api=SYNO.Docker.Container version=1 method=delete name=synology_gitlab_redis force=true preserve_profile=false
+/usr/syno/bin/synowebapi --exec api=SYNO.Docker.Container version=1 method=delete name=synology_gitlab force=true preserve_profile=false
 
-if [ -z "$CI_PARAPHRASE" ]; then
-	CI_PARAPHRASE="$(openssl rand -base64 48 | sed 's,/,_,g')"
-fi
-
-(
-	echo HTTP_PORT="\"$HTTP_PORT\""
-	echo SSH_PORT="\"$SSH_PORT\""
-	echo UNICORN_TIMEOUT="\"180\""
-	echo DB_NAME="\"$DB_NAME\""
-	echo DB_PASS="\"$DB_PASS\""
-	echo CI_PARAPHRASE="\"$CI_PARAPHRASE\""
-	echo HOSTNAME="\"$HOSTNAME\""
-	echo ADMIN_EMAIL="\"$ADMIN_EMAIL\""
-	echo SMTP_ENABLE="\"$SMTP_ENABLE\""
-	echo SMTP_ADDR="\"$SMTP_ADDR\""
-	echo SMTP_PORT="\"$SMTP_PORT\""
-	echo SMTP_USER="\"$SMTP_USER\""
-	echo SMTP_PASS="\"$SMTP_PASS\""
-	echo SMTP_VERIFY="\"$SMTP_VERIFY\""
-	echo SHARE="\"$SHARE\""
-) > "$ETC_PATH"/config
+docker rmi quay.io/sameersbn/redis:$REDIS_VERSION
+docker rmi quay.io/sameersbn/gitlab:$GITLAB_VERSION
 
 exit 0
